ANA_iter-master/projects/mysite/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

ANA_iter-master/projects/mysite/config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views
from page import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', include('mainpage.urls')),
    path('page/', include('page.urls')),
    path('planning/', views.plan, name='planning'),
    path('development/', views.dev, name='development'),
    path('sources/', views.sour, name='sources'),
    path('/index', base_views.index, name='index'),  # '/' 에 해당되는 path
]

ANA_iter-master/projects/mysite/mainpage/urls.py
from django.urls import path

from . import views

app_name = 'mainpage'

urlpatterns = [
    path('', views.index, name='index'),
]

ANA_iter-master/projects/mysite/page/urls.py
from django.urls import path
from . import views

app_name = 'page'

urlpatterns = [
    path('plan', views.plan, name='plan'),
    path('dev', views.dev, name='dev'),
    path('sour', views.sour, name='sour'),
]

ANA_iter-master/projects/mysite/pybo/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views

app_name = 'pybo'

urlpatterns = [
     # base_views.py
    path('',
         base_views.index, name='index'),
    path('<int:question_id>/',
         base_views.detail, name='detail'),

    # question_views.py
    path('question/create/',
         question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/',
         question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/',
         question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/',
         answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/',
         answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/',
         answer_views.answer_delete, name='answer_delete'),
]

ANA_iter-master/projects/mysite/pybo/models.py
from django.db import models
from django.contrib.auth.models import User

class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    
    def __str__(self):
        return self.subject

class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

ANA_iter-master/projects/mysite/pybo/forms.py
from django import forms
from pybo.models import Question, Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question  # 사용할 모델
        fields = ['subject', 'content']  # QuestionForm에서 사용할 Question 모델의 속성
        labels = {
            'subject': '제목',
            'content': '내용',
        }  
        

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

ANA_iter-master/projects/mysite/pybo/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import AnswerForm
from ..models import Question, Answer

@login_required(login_url='common:login')
def answer_create(request, question_id):
    """
    pybo 답변등록
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user  # author 속성에 로그인 계정 저장
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'pybo/question_detail.html', context)

@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    """
    pybo 답변수정
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('pybo:detail', question_id=answer.question.id)

    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('pybo:detail', question_id=answer.question.id)
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'pybo/answer_form.html', context)

@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    """
    pybo 답변삭제
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다')
    else:
        answer.delete()
    return redirect('pybo:detail', question_id=answer.question.id)

ANA_iter-master/projects/mysite/pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.db.models import Q

from ..models import Question

def index(request):
    """
    pybo 목록 출력
    """
    # 입력 파라미터
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어

    # 조회
    question_list = Question.objects.order_by('-create_date')
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목검색
            Q(content__icontains=kw) |  # 내용검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이검색
        ).distinct()
        
    # 페이징처리
    paginator = Paginator(question_list, 7)  # 페이지당 7개씩 보여주기
    page_obj = paginator.get_page(page)
    
    context = {'question_list': page_obj, 'page': page, 'kw': kw}
    return render(request, 'pybo/question_list.html', context)

def detail(request, question_id):
    """
    pybo 내용 출력
    """
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)

ANA_iter-master/projects/mysite/pybo/views/question_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import QuestionForm
from ..models import Question

@login_required(login_url='common:login')
def question_create(request):
    """
    pybo 질문등록
    """
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user  # author 속성에 로그인 계정 저장
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:index')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)

@login_required(login_url='common:login')
def question_modify(request, question_id):
    """
    pybo 질문수정
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('pybo:detail', question_id=question.id)

    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.modify_date = timezone.now()  # 수정일시 저장
            question.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)

@login_required(login_url='common:login')
def question_delete(request, question_id):
    """
    pybo 질문삭제
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('pybo:detail', question_id=question.id)
    question.delete()
    return redirect('pybo:index')

ANA_iter-master/projects/mysite/templates/pybo/answer_form.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/answer_form.css' %}">
<style>
    .intro_bg{
        background-image: url( "{% static 'image/intro2.jpg' %}");
    }
</style>
<div class="wrap">
    <div class="intro_bg">
        <div class="table_main0">
            <div class="table_main1">
                <br><br>
                <div class="container my-3">
                    <form method="post" class="post-form">
                        {% csrf_token %}
                        <!-- 오류표시 Start -->
                        {% if form.errors %}
                        <div class="alert alert-danger" role="alert">
                        {% for field in form %}
                            {% if field.errors %}
                            <strong>{{ field.label }}</strong>
                            {{ field.errors }}
                            {% endif %}
                        {% endfor %}
                        </div>
                        {% endif %}
                        <!-- 오류표시 End -->
                        <div class="form-group">
                            <label for="content">답변내용</label>
                            <textarea class="form-control" name="content" id="content" 
                                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
                        </div>
                        <button type="submit" class="btn_iter">저장하기</button>
                    </form>
                </div>
            </div>        
        </div>
    </div>
</div>
{% endblock %}

ANA_iter-master/projects/mysite/templates/pybo/question_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/question_detail.css' %}">
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
    />
    <title>ANA</title>
    <style>
        .intro_bg{
            background-image: url( "{% static 'image/intro2.jpg' %}");
        }
    </style>
    <script src="{% static 'jquery-3.4.1.min.js' %}"></script>
    <!-- Bootstrap JS -->
    <script src="{% static 'bootstrap.min.js' %}"></script>
</head>
<body>
    <div class="wrap">
        <div class="intro_bg">
            <div class="table_main0">
                <div class="table_main1">
                    <div class="subject">Q&A</div>
                    <div class="mini_subject">ANA 질문 목록 > {{ question.subject }}</div>
                    <div class="hr1"></div>
                    <!-- 사용자오류 표시 -->
                    {% if messages %}
                    <div class="alert alert-danger my-3" role="alert">
                    {% for message in messages %}
                        <strong>{{ message.tags }}</strong>
                        <ul><li>{{ message.message }}</li></ul>
                    {% endfor %}
                    </div>
                    {% endif %}
                    <h2 class="main_subject1">Q. {{ question.subject }}</h2>
                    <div class="question">
                        <div class="question_list">{{ question.content }}</div>
                        <div class="username">{{ question.author.username }}</div>
                        <div class="time">{{ question.create_date }}</div>
                        {% if request.user == question.author %}
                        <div class="btn_location">
                            <a href="{% url 'pybo:question_modify' question.id  %}" 
                            class="btn_iter btn-sm btn-outline-secondary">수정</a>
                            <a href="#" class="delete btn_iter btn-sm btn-outline-secondary"
       data-uri="{% url 'pybo:question_delete' question.id  %}">삭제</a>
                        </div>
                        {% endif %}
                    </div>
                    <h4 class="main_subject2">{{question.answer_set.count}}개의 답변이 있습니다.</h4>
                    <div class="hr2"></div>
                    {% for answer in question.answer_set.all %}
                    <div class="answer">
                        <div class="answer_list">A. {{ answer.content }}</div>
                        <div class="username">{{ answer.author.username }}</div>
                        <div class="time">{{ answer.create_date }}</div>
                        {% if request.user == answer.author %}
                        <div class="btn_location">
                            <a href="{% url 'pybo:answer_modify' answer.id  %}" 
                            class="btn_iter btn-sm btn-outline-secondary">수정</a>
                            <a href="#" class="delete btn_iter btn-sm btn-outline-secondary " 
               data-uri="{% url 'pybo:answer_delete' answer.id  %}">삭제</a>
                        </div>
                        {% endif %}
                    </div>
                    {% endfor %}
                    <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="answer_form">
                        {% csrf_token %}
                        {% if form.errors %}
                        <div class="answer_alert" role="alert">
                        {% for field in form %}
                            {% if field.errors %}
                            <strong>{{ field.label }}</strong>
                            {{ field.errors }}
                            {% endif %}
                        {% endfor %}
                        </div>
                        {% endif %}
                        <div class="form-group">
                            <textarea {% if not user.is_authenticated %}disabled{% endif %}
              name="content" id="content" class="form-control" rows="10"></textarea>
                        </div>
                        <input type="submit" value="답변등록" class="btn_iter">
                        <a href="{% url 'pybo:index' %}" class="btn_iter">돌아가기</a>
                    </form>
                </div>        
            </div>
        </div>
    </div>
    {% block script %}
    <script type='text/javascript'>
    $(document).ready(function(){
        $(".delete").on('click', function() {
            if(confirm("정말로 삭제하시겠습니까?")) {
                location.href = $(this).data('uri');
            }
        });
    });
    </script>
    {% endblock %}
</body>
</html>

ANA_iter-master/projects/mysite/templates/pybo/question_form.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/question_form.css' %}">
<style>
    .intro_bg{
        background-image: url( "{% static 'image/intro2.jpg' %}");
    }
</style>
<div class="wrap">
    <div class="intro_bg">
        <div class="table_main0">
            <div class="table_main1">
                <br><br>
                <div class="container">
                    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
                    <form method="post" class="post-form my-3">
                        {% csrf_token %}
                        <!-- 오류표시 Start -->
                        {% if form.errors %}
                        <div class="alert alert-danger" role="alert">
                        {% for field in form %}
                            {% if field.errors %}
                            <strong>{{ field.label }}</strong>
                            {{ field.errors }}
                            {% endif %}
                        {% endfor %}
                        </div>
                        {% endif %}
                        <!-- 오류표시 End -->
                        <div class="form-group">
                            <label for="subject">제목</label>
                            <input type="text" class="form-control" name="subject" id="subject"
                                value="{{ form.subject.value|default_if_none:'' }}">
                        </div>
                        <div class="form-group">
                            <label for="content">내용</label>
                            <textarea class="form-control" name="content"
                                    id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
                        </div>
                        <button type="submit" class="btn_iter">저장하기</button>
                        <a href="{% url 'pybo:index' %}" class="btn_1">돌아가기</a>
                    </form>
                </div>
            </div>        
        </div>
    </div>
</div>
{% endblock %}

ANA_iter-master/projects/mysite/templates/pybo/question_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/question_list.css' %}">
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
    />
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <script src="{% static 'jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'bootstrap.min.js' %}"></script>
    <title>ANA</title>
    <style>
        .intro_bg{
            background-image: url( "{% static 'image/intro2.jpg' %}");
        }
    </style>
    {% load pybo_filter %}
    <script type='text/javascript'>
        $(document).ready(function(){
            $(".page-link").on('click', function() {
                $("#page").val($(this).data("page"));
                $("#searchForm").submit();
            });
        
            $("#btn_search").on('click', function() {
                $("#kw").val($(".kw").val());
                $("#page").val(1);  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
                $("#searchForm").submit();
            });
        });
        </script>
</head>
<body>
    <div class="wrap">
        <div class="intro_bg">
            <div class="header" id="link_header">
                <ul class="nav">
                    <li><a class="nav-link_iter" href="{% url 'mainpage:index' %}">ANA</a></li>
                    {% if user.is_authenticated %}
                    <li><a class="nav-link_iter" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a></li>
                    {% else %}
                    <li><a class="nav-link_iter" href="{% url 'common:login' %}">로그인</a></li>
                    {% endif %}
                </ul>
                <div class="searchArea">
                    <form>
                        <input type="search" placeholder="Search" class="form-control kw" value="{{ kw|default_if_none:'' }}">
                        <span class="btn1_iter" type="button" id="btn_search">검색</span>
                    </form>
                </div>
            </div>
            <div class="table_main0">
                <div class="table_main1">
                    <div class="table_line1">
                        질문 게시판
                    </div>


                    <table class="table_iter">
                        <thead>
                        <tr class="text-center">
                            <th class="th_iter">번호</th>
                            <th class="th_iter" style="width:50%">제목</th>
                            <th class="th_iter">글쓴이</th>
                            <th class="th_iter">작성일시</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% if question_list %}
                        {% for question in question_list %}
                        <tr class="text-center">
                            <td class="td_iter">
                                <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                                {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
                            </td>
                            <td class="text-left td_iter">
                                <a class="a_iter" href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a>
                                {% if question.answer_set.count > 0 %}
                                <span class="text-danger_iter small ml-2">{{ question.answer_set.count }}</span>
                                {% endif %}
                            </td>
                            <td class="td_iter">{{ question.author.username }}</td>  <!-- 글쓴이 추가 -->
                            <td class="td_iter">{{ question.create_date }}</td>
                        </tr>
                        {% endfor %}
                        {% else %}
                        <tr>
                            <td class="td_iter" colspan="3">질문이 없습니다.</td>
                        </tr>
                        {% endif %}
                        </tbody>
                    </table>
                    <div class="pagination_iter">
                    <!-- 페이징처리 시작 -->
                    <ul class="pagination justify-content-center">
                        <!-- 이전페이지 -->
                        {% if question_list.has_previous %}
                        <li class="page-item">
                            <a class="page-link_iter" data-page="{{ question_list.previous_page_number }}" href="?page={{ question_list.previous_page_number }}">이전</a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a class="page-link_iter" tabindex="-1" aria-disabled="true" href="#">이전</a>
                        </li>
                        {% endif %}
                        <!-- 페이지리스트 -->
                        {% for page_number in question_list.paginator.page_range %}
                        {% if page_number >= question_list.number|add:-3 and page_number <= question_list.number|add:3 %}
                            {% if page_number == question_list.number %}
                            <li class="page-item active" aria-current="page">
                                <a class="page-link_iter" data-page="{{ page_number }}" href="?page={{ page_number }}">{{ page_number }}</a>
                            </li>
                            {% else %}
                            <li class="page-item">
                                <a class="page-link_iter" data-page="{{ page_number }}" href="?page={{ page_number }}">{{ page_number }}</a>
                            </li>
                            {% endif %}
                        {% endif %}
                        {% endfor %}
                        <!-- 다음페이지 -->
                        {% if question_list.has_next %}
                        <li class="page-item">
                            <a class="page-link_iter" data-page="{{ question_list.next_page_number }}" href="?page={{ question_list.next_page_number }}">다음</a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a class="page-link_iter" tabindex="-1" aria-disabled="true" href="#">다음</a>
                        </li>
                        {% endif %}
                    </ul>
                    <!-- 페이징처리 끝 -->
                    </div>

                    <a href="{% url 'pybo:question_create' %}" class="btn_iter">질문 등록하기</a>
                </div>
                <form id="searchForm" method="get" action="{% url 'index' %}">
                    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
                    <input type="hidden" id="page" name="page" value="{{ page }}">
                </form>
            </div>
        </div>
    </div>
</body>
</html>