ANA_iter-master/projects/mysite/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

ANA_iter-master/projects/mysite/config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views
from page import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', include('mainpage.urls')),
    path('page/', include('page.urls')),
    path('planning/', views.plan, name='planning'),
    path('development/', views.dev, name='development'),
    path('sources/', views.sour, name='sources'),
    path('/index', base_views.index, name='index'),  # '/' 에 해당되는 path
]

ANA_iter-master/projects/mysite/page/urls.py
from django.urls import path
from . import views

app_name = 'page'

urlpatterns = [
    path('plan', views.plan, name='plan'),
    path('dev', views.dev, name='dev'),
    path('sour', views.sour, name='sour'),
]

ANA_iter-master/projects/mysite/common/models.py
from django.db import models

# Create your models here.

ANA_iter-master/projects/mysite/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

ANA_iter-master/projects/mysite/common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm


def signup(request):
    """
    계정생성
    """
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

ANA_iter-master/projects/mysite/templates/common/login.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
<style>
    .intro_bg{
        background-image: url( "{% static 'image/intro2.jpg' %}");
    }
</style>
<div class="wrap">
    <div class="intro_bg">
        <div class="table_main0">
            <div class="table_main1">
                <br><br>
                <div class="container my-3">
                    <div class="row">
                        <div class="col-4">
                            <h4>로그인</h4>
                        </div>
                        <div class="col-8 text-right">
                            <span>또는 <a href="{% url 'common:signup' %}">계정을 만드세요.</a></span>
                        </div>
                    </div>
                    <form method="post" class="post-form" action="{% url 'common:login' %}">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ next }}">  <!-- 로그인 성공후 이동되는 URL -->
                        {% if form.errors %}
                            {% for field in form %}
                                {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
                                    <div class="alert alert-danger">
                                        <strong>{{ field.label }}</strong>
                                        {{ error }}
                                    </div>
                                {% endfor %}
                            {% endfor %}
                            {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
                                <div class="alert alert-danger">
                                    <strong>{{ error }}</strong>
                                </div>
                            {% endfor %}
                        {% endif %}
                        <div class="form-group">
                            <label for="username">사용자ID</label>
                            <input type="text" class="form-control" name="username" id="username"
                                   value="{{ form.username.value|default_if_none:'' }}">
                        </div>
                        <div class="form-group">
                            <label for="password">비밀번호</label>
                            <input type="password" class="form-control" name="password" id="password"
                                   value="{{ form.password.value|default_if_none:'' }}">
                        </div>
                        <button type="submit" class="btn_iter">로그인</button>
                    </form>
                </div>
            </div>        
        </div>
    </div>
</div>
{% endblock %}

ANA_iter-master/projects/mysite/templates/common/signup.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/signup.css' %}">
<style>
    .intro_bg{
        background-image: url( "{% static 'image/intro2.jpg' %}");
    }
</style>
<div class="wrap">
    <div class="intro_bg">
        <div class="table_main0">
            <div class="table_main1">
                <br><br>
                <div class="container my-3">
                    <div class="row my-3">
                        <div class="col-4">
                            <h4>계정생성</h4>
                        </div>
                        <div class="col-8 text-right">
                            <span>또는 <a href="{% url 'common:login' %}">로그인 하세요.</a></span>
                        </div>
                    </div>
                    <form method="post" class="post-form" action="{% url 'common:signup' %}">
                        {% csrf_token %}
                        {% if form.errors %}
                            {% for field in form %}
                                {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
                                    <div class="alert alert-danger">
                                        <strong>{{ field.label }}</strong>
                                        {{ error }}
                                    </div>
                                {% endfor %}
                            {% endfor %}
                            {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
                                <div class="alert alert-danger">
                                    <strong>{{ error }}</strong>
                                </div>
                            {% endfor %}
                        {% endif %}
                        <div class="form-group">
                            <label for="username">사용자 이름</label>
                            <input type="text" class="form-control" name="username" id="username"
                                   value="{{ form.username.value|default_if_none:'' }}">
                        </div>
                        <div class="form-group">
                            <label for="password1">비밀번호</label>
                            <input type="password" class="form-control" name="password1" id="password1"
                                   value="{{ form.password1.value|default_if_none:'' }}">
                        </div>
                        <div class="form-group">
                            <label for="password2">비밀번호 확인</label>
                            <input type="password" class="form-control" name="password2" id="password2"
                                   value="{{ form.password2.value|default_if_none:'' }}">
                        </div>
                        <div class="form-group">
                            <label for="email">이메일</label>
                            <input type="text" class="form-control" name="email" id="email"
                                   value="{{ form.email.value|default_if_none:'' }}">
                        </div>
                        <button type="submit" class="btn_iter">생성하기</button>
                    </form>
                </div>
            </div>        
        </div>
    </div>
</div>
{% endblock %}